
[Modules]

QRDExt_EngineeringModeDeviceInfo = yes
QRDExt_Extra_Wallpaper_gp = ct
#QRDExt_BrowserUA_gp = ct
QRDExt_PreloadApp_gp = ct
QRDExt_Launcher_Shortcut_gp = ct
QRDExt_BootAnimation_gp = ct
QRDExt_BootLogo_gp = ct
QRDExt_LauncherRes_gp = ct
QRDExt_BrowserRes_gp = ct
QRDExt_StkRes_gp = ct
QRDExt_BrowserQuick_gp = ct
QRDExt_CTCustomerService = yes
QRDExt_CTRoamingSettings = yes
QRDExt_PreLoadCacerts_gp = ct
QRDExt_QRDHiddenConfigMenu = yes
QRDExt_NoneSIMAlert = yes
QRDExt_Mail189 = yes
QRDExt_TraditionalChinese = yes
QRDExt_CDROM_RES_gp = ct
QRDExt_CT_FMC_Support = yes
QRDExt_FilterAppForMonkey_gp = ct
QRDExt_ResCustomization_gp = ct

[Java Feature]
FEATURE_EMAIL_DELETE_PROMPT = yes
FEATURE_EMAIL_LOAD_SPEC_PROVIDER = yes
FEATURE_EMAIL_ALERT_BEFORE_FORWARD = yes
FEATURE_EMAIL_SENDING_NOTIFICATION = yes
FEATURE_EMAIL_SPEC_ICON_FOR_NOTIFY = yes
FEATURE_SHOW_NETWORK_TYPE = yes
FEATURE_SHOW_DURATION_AFTER_CALL = yes
FEATURE_SHOW_PPP_DIAL_NUMBER = yes
FEATURE_MMS_SHARE_CONTACT = yes
FEATURE_MESSAGE_RESEND = yes
FEATURE_RESTRICT_SLOT2_DATA_SERVICE = yes
FEATURE_LAUNCHER_CUSTOM_SHOW_All_APP_OF_CT = yes
FEATURE_NOTIFICATION_BAR_NETWORK_CHOOSE = yes
FEATURE_NOTIFICATION_BAR_DATA_SWITCH = yes
FEATURE_USE_DEFAULT_PAGE = yes
FEATURE_BROWSER_SUPPORT_WAP2ESTORE = yes;
FEATURE_SHOW_EMERGENCY_CALL_SETTING = yes
FEATURE_BROWSER_DRM_UPLOAD_UNSUPPORT = yes
FEATURE_SUBSCRIPTION_CARRIER = yes
FEATURE_MMS_EDIT_SMSC = yes
FEATURE_LAUNCHER_CONTROL_MAIL189 = yes
FEATURE_CALLLOG_CDMA_ACTIVETIME = yes
FEATURE_DUAL_SIM_DATA_USAGE = yes
FEATURE_DISABLE_MMSC = yes
FEATURE_ALLOW_DOWNLOAD_ALL = yes
FEATURE_COPY_EXTRACT_URL = yes
FEATURE_MMS_NEARLY_FULLNOTIFICATION = yes
FEATURE_MMS_NEW_MESSAGE_NOTIFI_BY_UNREAD = yes
FEATURE_MMS_MESSAGE_COUNT_LIMIT = yes
FEATURE_MMS_FILTER_RECIPIENTS_CHARACTER = yes;
FEATURE_MMS_MMS_DOWNLOAD_LIMIT = yes;
FEATURE_SHOW_CARRIER_BY_MCCMNC = yes;
FEATURE_SETTINGS_SHOW_DEFAULT_APN = yes;
FEATURE_SETTINGS_APN_AUTOSELECT_CTNET = yes;
FEATURE_PHONE_CALL_FORWARDING_CONSOLIDATION = yes;
FEATURE_SHOW_SIM_NETWORK_UNLOCK = yes;
FEATURE_SET_NV_GLOBAL_MODE = yes;
FEATURE_SMS_PRIORITY = yes;
FEATURE_SHOW_EMERGENCY_NO = yes;
FEATURE_CT_FMC_SUPPORT = yes;
FEATURE_SETTINGS_CLOSE_ENG_MODE = yes;
FEATURE_SMS_DUAL_MODE_CARD = yes;
FEATURE_DOWNLOADPROVIDER_SUPPORT_BREAKPOINT_CONTINUINGLY = yes;
FEATURE_EMAIL_SHOW_ORIGINAL_MAIL = yes;
FEATURE_PHONE_CANNOT_SELECT_NETWORK = yes;
FEATURE_PHONE_DONOT_SHOW_NOTIFY = yes;
FEATURE_SETTINGS_SIM_NAME_AS_SLOT_NAME = yes;
FEATURE_RETRY_ALWAYS = yes;
FEATURE_BAIDU_XCLOUD = yes;
FEATURE_SHOW_NOTI_IN_THREAD = yes;
[Native Feature]
ENABLE_QRDEXT_AUTO_REG_SMS = yes
ENABLE_QRDEXT_CT_EMERGENCY_CALL_REG = yes
ENABLE_QRDEXT_GLOBAL_MODE = yes
ENABLE_QRDEXT_CT_FMC_SUPPORT = yes

[Java Default Value]
BROWSER_DEFAULT_TEXT_ENCODING = "GBK"; // the default text encoding
STATUSBAR_STYLE = 2; // China Telecom status bar style
LOAD_SPEC_PROVIDER = "ct"; // Chine Telecom spec provider

[Native Default Value]
QRDEXT_REG_SMS_OPERATOR = "CT"; // operator value for auto reg sms
